title: ""
# author: Cash Compton
# email: cash@cashc.me
description: Some thoughts I think are nice

# social links
# twitter_username: CashCompton
github_username: cashc
# rss: rss
# dribbble_username: jekyll
# facebook_username: cash.money.compton
# flickr_username: jekyll
instagram_username: cash_hola
# linkedin_username: jekyll
# pinterest_username: jekyll
# youtube_username: jekyll
# googleplus_username: +jekyll

# Mastodon instances
# mastodon:
# - username: jekyll
#   instance: example.com
# - username: jekyll2
#   instance: example.com

google_analytics: UA-160724040-1

disqus:
  shortname: think-nicely

show_excerpts: true # set to true to show excerpts on the homepage

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
# header_pages:
# - build.html

# Build settings
markdown: kramdown
theme: minima
exclude:
  - Gemfile
  - Gemfile.lock
include:
  - /public/

collections:
  vanbuild:
    output: true
